<?php

// migrations/001_create_initial_tables.php

return [
    "up" => function($pdo) {
        $pdo->exec("CREATE TABLE IF NOT EXISTS `users` (`id` INT AUTO_INCREMENT PRIMARY KEY, `name` VARCHAR(255) NOT NULL, `email` VARCHAR(255) NOT NULL UNIQUE, `phone` VARCHAR(20) NOT NULL, `password` VARCHAR(255) NOT NULL, `passcode` VARCHAR(255), `tier` INT DEFAULT 1, `wallet_balance` DECIMAL(10, 2) DEFAULT 0.00, `bonus_balance` DECIMAL(10, 2) DEFAULT 0.00, `referral_link` VARCHAR(255), `referred_by` INT, `status` VARCHAR(20) DEFAULT 'active', `is_verified` BOOLEAN DEFAULT FALSE, `api_key` VARCHAR(255), `api_enabled` BOOLEAN DEFAULT FALSE, `last_login` TIMESTAMP NULL, `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, `user_level` INT DEFAULT 0, `paystack_account` VARCHAR(20), `paystack_bank` VARCHAR(100), `bvn` VARCHAR(11), `nin` VARCHAR(11))");
        $pdo->exec("CREATE TABLE IF NOT EXISTS `email_verifications` (`id` INT AUTO_INCREMENT PRIMARY KEY, `user_id` INT NOT NULL, `token` VARCHAR(255) NOT NULL UNIQUE, `expires` DATETIME NOT NULL, `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS `transactions` (`id` INT AUTO_INCREMENT PRIMARY KEY, `user_id` INT NOT NULL, `type` VARCHAR(50) NOT NULL, `description` VARCHAR(255) NOT NULL, `amount` DECIMAL(10, 2) NOT NULL, `status` VARCHAR(50) NOT NULL, `service_details` TEXT, `source` VARCHAR(20) DEFAULT 'Website', `balance_before` DECIMAL(10, 2), `balance_after` DECIMAL(10, 2), `batch_id` VARCHAR(255), `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS `withdrawals` (`id` INT AUTO_INCREMENT PRIMARY KEY, `user_id` INT NOT NULL, `amount` DECIMAL(10, 2) NOT NULL, `bank_details` TEXT NOT NULL, `status` VARCHAR(20) DEFAULT 'pending', `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS `fund_shares` (`id` INT AUTO_INCREMENT PRIMARY KEY, `sender_id` INT NOT NULL, `recipient_id` INT NOT NULL, `amount` DECIMAL(10, 2) NOT NULL, `status` VARCHAR(20) DEFAULT 'pending', `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (recipient_id) REFERENCES users(id) ON DELETE CASCADE)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS `notifications` (`id` INT AUTO_INCREMENT PRIMARY KEY, `user_id` INT, `title` VARCHAR(255) NOT NULL, `message` TEXT NOT NULL, `is_read` BOOLEAN DEFAULT FALSE, `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS `bank_details` (`id` INT AUTO_INCREMENT PRIMARY KEY, `bank_name` VARCHAR(255) NOT NULL, `account_name` VARCHAR(255) NOT NULL, `account_number` VARCHAR(20) NOT NULL, `charge` DECIMAL(10, 2) DEFAULT 0.00, `instructions` TEXT)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS `payment_orders` (`id` INT AUTO_INCREMENT PRIMARY KEY, `user_id` INT NOT NULL, `bank_id` INT, `amount` DECIMAL(10, 2) NOT NULL, `payment_proof` TEXT, `status` VARCHAR(20) DEFAULT 'pending', `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (bank_id) REFERENCES bank_details(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS `site_settings` (`id` INT AUTO_INCREMENT PRIMARY KEY, `site_name` VARCHAR(255) DEFAULT 'My VTU', `site_logo` VARCHAR(255), `auth_image` VARCHAR(255), `session_timeout` INT DEFAULT 30, `cache_control` VARCHAR(255) DEFAULT 'no-cache', `referral_bonus_tier1` DECIMAL(5, 2) DEFAULT 0.00, `referral_bonus_tier2` DECIMAL(5, 2) DEFAULT 0.00, `admin_email` VARCHAR(255) DEFAULT 'admin@example.com')");
        $pdo->exec("CREATE TABLE IF NOT EXISTS `services` (`id` INT AUTO_INCREMENT PRIMARY KEY, `name` VARCHAR(100) NOT NULL, `config` TEXT NOT NULL)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS `bonus_withdrawals` (`id` INT AUTO_INCREMENT PRIMARY KEY, `user_id` INT NOT NULL, `amount` DECIMAL(10, 2) NOT NULL, `bank_details` TEXT NOT NULL, `status` VARCHAR(20) DEFAULT 'pending', `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS `admins` (`id` INT AUTO_INCREMENT PRIMARY KEY, `name` VARCHAR(255) NOT NULL, `email` VARCHAR(255) NOT NULL UNIQUE, `password` VARCHAR(255) NOT NULL, `last_login` TIMESTAMP NULL, `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS `user_read_notifications` (`id` int(11) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL, `notification_id` int(11) NOT NULL, `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`), UNIQUE KEY `user_notification` (`user_id`,`notification_id`), KEY `user_id` (`user_id`), KEY `notification_id` (`notification_id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;");
        $pdo->exec("CREATE TABLE IF NOT EXISTS `password_resets` (`id` INT AUTO_INCREMENT PRIMARY KEY, `email` VARCHAR(255) NOT NULL, `token` VARCHAR(255) NOT NULL, `expires` DATETIME NOT NULL, `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS `chat` (`id` INT AUTO_INCREMENT PRIMARY KEY, `sender_id` INT NOT NULL, `recipient_id` INT NOT NULL, `message` TEXT NOT NULL, `is_read` BOOLEAN DEFAULT FALSE, `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS `transaction_limits` (`id` INT AUTO_INCREMENT PRIMARY KEY, `identifier_type` VARCHAR(50) NOT NULL, `identifier_value` VARCHAR(100) NOT NULL, `limit_type` VARCHAR(50) NOT NULL, `limit_value` DECIMAL(15,2) NOT NULL, `max_transactions` INT DEFAULT NULL, `created_by` INT, `period_type` VARCHAR(50) DEFAULT 'daily', `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP NULL DEFAULT NULL, FOREIGN KEY (`created_by`) REFERENCES admins(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS `blocked_identifiers` (`id` INT AUTO_INCREMENT PRIMARY KEY, `identifier_type` VARCHAR(50) NOT NULL, `identifier_value` VARCHAR(100) NOT NULL, `reason` TEXT, `blocked_by` INT, `blocked_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, `unblocked_at` TIMESTAMP NULL DEFAULT NULL, `status` VARCHAR(20) DEFAULT 'blocked')");
        $pdo->exec("CREATE TABLE IF NOT EXISTS `senderid_requests` (`id` INT AUTO_INCREMENT PRIMARY KEY, `user_id` INT NOT NULL, `sender_id` VARCHAR(50) NOT NULL, `sample_message` TEXT, `status` VARCHAR(20) DEFAULT 'pending', `moderated_by` INT, `moderated_at` TIMESTAMP NULL DEFAULT NULL, `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS `sms_sender_ids` (`id` INT AUTO_INCREMENT PRIMARY KEY, `sender_id` VARCHAR(20) NOT NULL, `status` ENUM('pending', 'approved', 'blocked') DEFAULT 'pending', `requested_by` INT, `requested_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, `approved_by` INT DEFAULT NULL, `approved_at` TIMESTAMP NULL DEFAULT NULL, `blocked_reason` VARCHAR(255) DEFAULT NULL, `reviewed_by` INT DEFAULT NULL, `user_id` INT DEFAULT NULL, `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP);");
    },
    "down" => function($pdo) {
        // Drop tables in reverse order of creation
    }
];
